
version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: producttable
      MYSQL_USER: newuser
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - "my-network"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1","-u","newuser","-p${MYSQL_PASSWORD}" ]
      timeout: 5s
      retries: 5
  java-app:
      build: .
      container_name: java-app
      depends_on:
          mysql-db:
            condition: service_healthy
      ports:
          - "8080:8080"
      environment:
        DB_URL: jdbc:mysql://mysql-db:3306/producttable?allowPublicKeyRetrieval=true&useSSL=false
        DB_USER: newuser
        DB_PASSWORD: root
      networks:
          - "my-network"

networks:
    my-network:
